default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
development:
  <<: *default
  database: simple-todos_development
test:
  <<: *default
  database: simple-todos_test
production:
  <<: *default
  database: simple-todos_production
  username: simple-todos
  password: <%= ENV['SIMPLE-TODOS_DATABASE_PASSWORD'] %>
